---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-pihole
  namespace: network
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-dns-pihole
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: external-dns-pihole

    domainFilters:
      - kalde.in

    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: external-dns-pihole-secret
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://192.168.10.80
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        value: "6"

    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint

    interval: 1m
    logLevel: info
    logFormat: text

    policy: sync
    provider: pihole

    registry: txt
    txtOwnerId: main-cluster-pihole
    txtPrefix: main-

    sources:
      - crd
      - gateway-httproute

    serviceMonitor:
      enabled: true
