apiVersion: v1
kind: Secret
metadata:
  name: external-dns-pihole-secret
  namespace: network
type: Opaque
stringData:
  EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:EALJs7M/Oi252VEbqVPL8QFYbVl9DzfSljLDWIQrM4RK4C2p7YGRHqwUIgQ=,iv:wKYi/aq1WIWzizMBPwGznTptJjHQ6OtH1Tl2Y6YcNgc=,tag:pFe67LrbpumcOvsdqVMf0g==,type:str]
sops:
  age:
    - recipient: age1rpavzet35zr3pgqcvz9emvgmuzlc5w9w2cjwl86arr406c6hlaqqszqt2u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVDdqS1g3Mnhjekx4TGQ1
        L0JDeWdubnR6Nmtna2I4Z0Z1M290RmVFa1ZNCmF6QTlIUmVOSkhJdEN5WTVrb3d1
        dmZuZ3piVmIxbnJDSDFHMWFOVU01WTgKLS0tIER6ck1zbHREeFA3NTA3bG5EcGVr
        eWhucnNpbVdNcHhVUTl5VDUxOFpyS1kKQwadYdliXl+jWLM4gDxRa3ncs+83WrM3
        w92I+bjXkRW//a4u8e7JfBZ0mEXmZR83Ya7OXOTyrYXIDutfYiDHFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T17:02:50Z"
  mac: ENC[AES256_GCM,data:F3yUTEtffi8zy6bd+iL4PL7+hlHm/rPDVeia9S4EVushceTkpHZgoiqNE9s5+Ek915OGF+mN63fX91CvWu8L96ZPmt6JzDg0sJjBjQx5nO/E77TSAez5dori9fo+LeQEMCgYfrOvBm0C1NyiB8/W/sBN5h7BV++5huZg3vP5UxY=,iv:B+AxWIKMSO566SP9ChttyY6eDsbrOD4oq9BomVAY3nU=,tag:1xKC9FlM9InsXybX4bPjWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
