---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opencloud
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: opencloud
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      opencloud:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        strategy: RollingUpdate
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init:
            image:
              repository: opencloudeu/opencloud-rolling
              tag: latest
            command: [sh, -c, "opencloud init || true"]
            envFrom: &envFrom
              - secretRef:
                  name: opencloud-secret
            env: &env
              OC_URL: https://cloud.kalde.in
              PROXY_HTTP_ADDR: 0.0.0.0:9200
              OC_INSECURE: "true"
              PROXY_TLS: "false"
        containers:
          app:
            image:
              repository: opencloudeu/opencloud-rolling
              tag: latest
            env:
              <<: *env
              COLLABORA_DOMAIN: office.kalde.in
              NATS_NATS_HOST: 0.0.0.0
              GATEWAY_GRPC_ADDR: 0.0.0.0:9142
              FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1024Mi
          collaboration:
            image:
              repository: opencloudeu/opencloud-rolling
              tag: latest
            command: ["opencloud", "collaboration", "server"]
            env:
              COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
              COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
              MICRO_REGISTRY: nats-js-kv
              MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
              COLLABORATION_WOPI_SRC: https://wopi.kalde.in
              COLLABORATION_APP_NAME: CollaboraOnline
              COLLABORATION_APP_PRODUCT: Collabora
              COLLABORATION_APP_ADDR: https://office.kalde.in
              COLLABORATION_APP_ICON: https://office.kalde.in/favicon.ico
              COLLABORATION_APP_INSECURE: "true"
              COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
              OC_URL: https://cloud.kalde.in

    service:
      app:
        ports:
          http:
            port: &port 9200
          wopi:
            port: &wopiPort 9300

    route:
      app:
        hostnames: ["cloud.kalde.in"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
      wopi:
        hostnames: ["wopi.kalde.in"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *wopiPort

    persistence:
      config:
        enabled: true
        existingClaim: opencloud-config
        globalMounts:
          - path: /etc/opencloud
      data:
        enabled: true
        existingClaim: opencloud-data
        globalMounts:
          - path: /var/lib/opencloud
