---
# Internal DNS record for Pi-hole - points to internal gateway IP
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: prometheus-pihole
  namespace: observability
  annotations:
    external-dns.alpha.kubernetes.io/target: "192.168.10.252"
spec:
  endpoints:
    - dnsName: prometheus.kalde.in
      recordTTL: 300
      recordType: A
      targets:
        - 192.168.10.252  # main cluster internal gateway
