---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: invoiceninja-secret
  namespace: invoiceninja
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: invoiceninja-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        APP_KEY: "{{ .app_key }}"
        DB_DATABASE: "{{ .db_database }}"
        DB_USERNAME: "{{ .db_user }}"
        DB_PASSWORD: "{{ .db_password }}"
  dataFrom:
    - extract:
        key: invoiceninja
