---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./akaunting/ks.yaml
  - ./changedetection/ks.yaml
  - ./consolewiki/ks.yaml
  - ./dailytrace/ks.yaml
  - ./echo/ks.yaml
  - ./home-assistant/ks.yaml
  - ./immich/ks.yaml
  - ./kapowarr/ks.yaml
  - ./kavita/ks.yaml
  - ./kometa/ks.yaml
  - ./linkding/ks.yaml
  #- ./longhorn/ks.yaml
  - ./miniflux/ks.yaml
  - ./n8n/ks.yaml
  - ./nextcloud/ks.yaml
  - ./paperless-ngx/ks.yaml
  - ./peppermint/ks.yaml
  - ./sync-todoist-to-habitica/ks.yaml
  - ./teslamate/ks.yaml
  - ./wallabag/ks.yaml
