---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr-db-backup-logs
  namespace: media
spec:
  interval: "30m"
  chartRef:
    kind: OCIRepository
    name: radarr-db-backup-logs
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      backup:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@daily"
        containers:
          app:
            image:
              repository: casmith/pgsqldump
              tag: v0.2.0
            env:
              DB_NAME: radarr_log
              FLAGS: "-Fc"
              DB_HOST: postgres17-rw.database.svc.cluster.local
            envFrom:
              - secretRef:
                  name: radarr-db-backup-secret
            restartPolicy: OnFailure
    service:
      backup:
        enabled: false
    persistence:
      backup:
        enabled: true
        type: nfs
        server: 192.168.10.3
        path: /volume1/cluster/db-backup/radarr
        globalMounts:
          - path: /pgsqldump
