---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: collabora
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: collabora-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        COLLABORA_ADMIN_USER: "{{ .COLLABORA_ADMIN_USER }}"
        COLLABORA_ADMIN_PASSWORD: "{{ .COLLABORA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: collabora
  refreshInterval: 5m
