---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: seaweedfs-s3-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        seaweedfs_s3_config: |
          {
            "identities": [
              {
                "name": "{{ .admin_access_key }}",
                "credentials": [
                  {
                    "accessKey": "{{ .admin_access_key }}",
                    "secretKey": "{{ .admin_secret_key }}"
                  }
                ],
                "actions": [
                  "Admin",
                  "Read",
                  "Write"
                ]
              },
              {
                "name": "{{ .terraform_access_key }}",
                "credentials": [
                  {
                    "accessKey": "{{ .terraform_access_key }}",
                    "secretKey": "{{ .terraform_secret_key }}"
                  }
                ],
                "actions": [
                  "Read",
                  "List",
                  "Write"
                ],
                "buckets": ["terraform-state"]
              },
              {
                "name": "{{ .backup_access_key }}",
                "credentials": [
                  {
                    "accessKey": "{{ .backup_access_key }}",
                    "secretKey": "{{ .backup_secret_key }}"
                  }
                ],
                "actions": [
                  "Read",
                  "List",
                  "Write"
                ],
                "buckets": ["beoftexas-backup"]
              }

            ]
          }
  dataFrom:
    - extract:
        key: seaweedfs
