---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs
  namespace: storage
spec:
  interval: 1h
  url: https://seaweedfs.github.io/seaweedfs/helm
